// /*
//  * This Kotlin source file was generated by the Gradle 'init' task.
//  */
// package andr3.app

// import andr3.utilities.StringUtils

// import org.apache.commons.text.WordUtils

// fun main() {
//     val tokens = StringUtils.split(MessageUtils.getMessage())
//     val result = StringUtils.join(tokens)
//     println(WordUtils.capitalize(result))
// }


// Hello World Program

fun main(args : Array<String>) {
        println("Hello, World!")
}